baseURL: "https://twineworks.github.io/tweakflow/"
languageCode: "en-us"
title: "tweakflow - an embeddable expression language for the JVM"
theme: "hugo-tweakflow"
uglyurls: true
# relativeURLs: true
menu:
  main:
    - Name: "Getting started"
      URL: "/getting-started.html"
      Weight: -600

    - Name: "Reference"
      URL: "/reference.html"
      Weight: -500

    - Name: "Standard library"
      URL: "/modules/std.html"
      Weight: -400

    - Name: "Embedding guide"
      URL: "/embedding.html"
      Weight: -300

    - Name: "Source code"
      URL: "https://github.com/twineworks/tweakflow/"
      Weight: -100



params:
  indexHeadLine: "index headline parameter"
